import { chromium } from "playwright";
const base = "http://localhost:4173";
const R = "/home/user/standard-Plus-/lovable-ueberarbeitung/.impeccable/review";
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium" });
let fehler = 0;
const ok = (bed, t) => { console.log((bed ? "OK   " : "FEHLT") + " " + t); if (!bed) fehler++; };
const p = await (await b.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, locale: "de-DE" })).newPage();
const logs = []; p.on("pageerror", (e) => logs.push(e.message)); p.on("console", (m) => { if (m.type() === "error") logs.push(m.text()); });
await p.goto(base + "/"); await p.evaluate(() => localStorage.setItem("test-rolle", "arbeitnehmer"));
await p.goto(base + "/profil-bearbeiten", { waitUntil: "networkidle" });
ok(await p.getByRole("heading", { name: "Angaben aus der Registrierung" }).isVisible(), "Identität als eigener Block");
ok(await p.getByText("Test Person").isVisible() && await p.getByText("12.03.1994").isVisible(), "Name und Geburtsdatum angezeigt");
ok(await p.locator("#vorname").count() === 0 && await p.locator("#geburtsjahr").count() === 0, "Name/Geburtsjahr nicht mehr bearbeitbar");
ok(await p.getByText("Freiwillig: Mein Alter (in Jahren) im Profil anzeigen.").isVisible(), "Alter-Schalter vorhanden");
ok(!(await p.getByRole("checkbox", { name: /Mein Alter/ }).isChecked()), "Alter standardmäßig aus");
ok(await p.getByText(/Foto/).first().isVisible(), "Foto-Bereich sichtbar");
ok(!(await p.evaluate(() => document.documentElement.scrollWidth > innerWidth)), "Handy: keine seitliche Scrollleiste");
await p.screenshot({ path: R + "/profil-bearbeiten.png", fullPage: true });
await p.goto(base + "/profil/11111111-0000-4000-8000-000000000001", { waitUntil: "networkidle" });
ok(await p.getByRole("heading", { name: /Maria .*, 38/ }).isVisible(), "Profil: Name mit Alter (wenn freigegeben)");
ok(await p.getByLabel("Ausweis geprüft").first().isVisible(), "Profil: Abzeichen Ausweis geprüft");
// Teststub kennt keine Zugriffsregeln (RLS) und liefert Kontaktdaten immer – darum hier nur: Kontaktbereich vorhanden
ok(await p.getByRole("heading", { name: "Kontakt" }).isVisible(), "Kontaktbereich vorhanden");
ok(!(await p.evaluate(() => document.documentElement.scrollWidth > innerWidth)), "Profil: keine seitliche Scrollleiste");
await p.screenshot({ path: R + "/profil-ansicht.png", fullPage: true });
ok(logs.length === 0, "Keine Fehler" + (logs.length ? ": " + logs.join(" | ") : ""));
await b.close();
console.log(fehler ? `\n${fehler} Prüfung(en) fehlgeschlagen` : "\nAlle Prüfungen bestanden");
process.exit(fehler ? 1 : 0);
