import { chromium } from "playwright";
const base = "http://localhost:4173";
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium" });
let fehler = 0;
const ok = (bed, t) => { console.log((bed ? "OK   " : "FEHLT") + " " + t); if (!bed) fehler++; };
const p = await (await b.newContext({ viewport: { width: 390, height: 844 }, locale: "de-DE" })).newPage();
const logs = []; p.on("pageerror", (e) => logs.push(e.message));
let skript = false; p.on("request", (r) => { if (r.url().includes("challenges.cloudflare.com")) skript = true; });
await p.goto(base + "/auth", { waitUntil: "networkidle" });
ok(!skript, "Ohne Schlüssel wird kein Cloudflare-Skript geladen");
await p.locator("#land").selectOption("NG");
ok(await p.getByText("Für dieses Land verschicken wir keine SMS-Codes.").isVisible(), "Nigeria: Hinweis statt SMS");
await p.locator("input[type=tel]").fill("8012345678");
await p.getByRole("button", { name: /Code senden|Code per SMS/ }).first().click();
await p.waitForTimeout(300);
ok(await p.getByText("Für dieses Land verschicken wir keine SMS. Bitte nutzen Sie E-Mail").first().isVisible(), "Kein SMS-Versand nach Nigeria");
await p.getByRole("button", { name: "Mit E-Mail fortfahren" }).click();
ok(await p.locator("input[name=email]").isVisible(), "Wechsel auf E-Mail");
await p.getByRole("button", { name: "Mit Handynummer" }).click();
await p.locator("#land").selectOption("RO");
ok(await p.getByText("Für dieses Land verschicken wir keine SMS-Codes.").count() === 0, "Rumänien: SMS erlaubt");
// Antwort der Kostenbremse wird verständlich angezeigt (Stub: Nummern auf …999 = Festnetz, …888 = Tageslimit)
await p.locator("input[type=tel]").fill("1712345999");
await p.getByRole("button", { name: /Code senden|Code per SMS/ }).first().click();
await p.waitForTimeout(300);
ok(await p.getByText("An diese Nummer können wir keine SMS schicken (Festnetz- oder Sondernummer).").first().isVisible(), "Festnetz-Hinweis vom Server");
await p.locator("input[type=tel]").fill("1712345888");
await p.getByRole("button", { name: /Code senden|Code per SMS/ }).first().click();
await p.waitForTimeout(300);
ok(await p.getByText("Heute können wir keine weiteren SMS verschicken.").first().isVisible(), "Tageslimit-Hinweis vom Server");
ok(logs.length === 0, "Keine Fehler" + (logs.length ? ": " + logs.join(" | ") : ""));
await b.close();
console.log(fehler ? `\n${fehler} Prüfung(en) fehlgeschlagen` : "\nAlle Prüfungen bestanden");
process.exit(fehler ? 1 : 0);
